apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: the-project-fe-configmap
data:
  PORT: "8000"
  TODO_BACKEND_URL: "http://the-project-be-svc:1235"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: the-project-be-configmap
data:
  PORT: "8001"
  NATS_URL: "nats://nats-svc:4222"

  POSTGRES_HOST: pg-svc.project.svc.cluster.local
  db.sh: |
    #!/bin/bash
    echo "Success start";

    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "my_db" <<-EOSQL
      CREATE DATABASE todolist_db;
      GRANT ALL PRIVILEGES ON DATABASE todolist_db TO postgres;

      \c todolist_db;

      CREATE TABLE IF NOT EXISTS public.todolist_table (
          id BIGSERIAL PRIMARY KEY,
          name character varying(100) COLLATE pg_catalog."default" NOT NULL,
          status integer NOT NULL,
          CONSTRAINT todolist_table_pkey PRIMARY KEY (id)
      );
  
      INSERT into todolist_table (id, name, status) VALUES ('1', 'task 11', 1);
      INSERT into todolist_table (id, name, status) VALUES ('2', 'task 22', 0);
      INSERT into todolist_table (id, name, status) VALUES ('3', 'task 33', 0);
    EOSQL

    echo "Success end";