apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: the-project-pvc # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: the-project-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi