apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: broadcaster
        env:
        - name: ENVIRONMENT
          value: "staging"
